### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by Orkin**
Package ~2.3 not available in stable version

### CODE REVIEW

**Comment by bakura10** [comment]
Very strange. Ping @ocramius

**Comment by Orkin** [comment]
Your requirements could not be resolved to an installable set of packages.
php composer.phar create-project -sdev maestrooo/zend-skeleton-light my-path

  Problem 1
    - The requested package zendframework/zendframework could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by Ocramius** [comment]
What is your full composer.json? Just the original one? PHP version? Is composer up to date?

**Comment by Orkin** [comment]
The same as the project, composer up to date and php 5.4

**Comment by Ocramius** [comment]
What does travis say about that?

The same as the project, composer up to date and php 5.4

**Pull request closed without merging**
